export const EXAMPLE_TABLE_COL = [
  {
    name: "Title",
    selector: (row) => row.title,
    sortable: true,
  },
  {
    name: "Year",
    selector: (row) => row.year,
    sortable: true,
  },
];

export const EXAMPLE_TABLE_DATA = [
  { id: 1, title: "Beetlejuice", year: "1988" },
  { id: 2, title: "Ghostbusters", year: "1984" },
  { id: 3, title: "Back to the Future", year: "1985" },
  { id: 4, title: "E.T.", year: "1982" },
  { id: 5, title: "The Goonies", year: "1985" },
  { id: 6, title: "The Breakfast Club", year: "1985" },
  { id: 7, title: "Ferris Bueller's Day Off", year: "1986" },
  { id: 8, title: "Die Hard", year: "1988" },
  { id: 9, title: "Terminator", year: "1984" },
  { id: 10, title: "Aliens", year: "1986" },
  { id: 11, title: "The Karate Kid", year: "1984" },
  { id: 12, title: "Raiders of the Lost Ark", year: "1981" },
  { id: 13, title: "The Empire Strikes Back", year: "1980" },
  { id: 14, title: "Return of the Jedi", year: "1983" },
  { id: 15, title: "Blade Runner", year: "1982" },
  { id: 16, title: "Top Gun", year: "1986" },
  { id: 17, title: "RoboCop", year: "1987" },
  { id: 18, title: "The Thing", year: "1982" },
  { id: 19, title: "The Shining", year: "1980" },
  { id: 20, title: "Poltergeist", year: "1982" },
  { id: 21, title: "Scarface", year: "1983" },
  { id: 22, title: "Gremlins", year: "1984" },
  { id: 23, title: "The Fly", year: "1986" },
  { id: 24, title: "Lethal Weapon", year: "1987" },
  { id: 25, title: "The Lost Boys", year: "1987" },
  { id: 26, title: "Stand by Me", year: "1986" },
  { id: 27, title: "The Princess Bride", year: "1987" },
  { id: 28, title: "The NeverEnding Story", year: "1984" },
  { id: 29, title: "The Terminator", year: "1984" },
  { id: 30, title: "Indiana Jones and the Last Crusade", year: "1989" },
];
